NewsFileUK:
    FileName: UK_newspapers.xlsx
    SheetName: News
    SaveAs: uk_news.csv
NewsFileUK_2:
    FileName: UK_newspapers_sample2.xlsx
    SheetName: News
    SaveAs: uk_news_sample2.csv
Fields:
    - Title
    - Published date
    - Publication location
    - Publication
    - Publication type
    - Length
    - Section
    - Word count
    - Countries
    - Byline
    - Agg-copyright
    - Cite
    - Company
    - Headline
    - Hlead
    - Publication 2
    - Publication type 2
    - Pub-copyright
    - Show
    - Term
    - Ticker
FieldsToKeep:
    - Title
    - Published date
    - Publication location
    - Publication
    - Length
    - Word count
    - Countries
    - Byline
    - Headline
    - Hlead
    - Publication type 2
FieldsNewNames:
    - title
    - pub_date
    - pub_location
    - pub_name
    - length
    - word_count
    - countries
    - byline
    - headline
    - full_text
    - pub_type
