FileBatch1:
  FileName: kw_sentiment_batch1.xlsx
  SheetNames:
    - sample_0-15_200-210
    - sample_16-199
    - sample_211-350
    - sample_quoted_keywords
    - sample_351-480
    - sample_481-605
  ExpectedCols:
    - 'article_id' 
    - 'title' 
    - 'pub_date' 
    - 'full_text' 
    - 'kword' 
    - 'opinion_context' 
    - 'opinion_context_id'
    - 'keyword_sentiment' 
    - 'refers_to_gov'
    - 'gov_sentiment'
FileBatch2:
  FileName: kw_sentiment_batch2.xlsx
  SheetNames:
    - sample1
    - sample2
    - sample3
  ExpectedCols:
    - 'article_id' 
    - 'title' 
    - 'pub_date' 
    - 'full_text' 
    - 'kword' 
    - 'opinion_context' 
    - 'opinion_context_id'
    - 'keyword_sentiment' 
    - 'refers_to_gov'
    - 'gov_sentiment'
Outputname: kword_sentiments_coded.csv